name             'base'
maintainer       'MADACS'
maintainer_email 'marc5.12@outlook.com'
license          'Apache 2.0'
description      'Installs/Configures base state for all nodes'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'chef-client'
depends          'ntp'
depends          'apt'
depends          'yum'